// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CreateEvent defines model for CreateEvent.
type CreateEvent struct {
	// Address Smart contract address from which the event was emitted
	Address string `json:"address"`

	// Name Name of the event
	Name string `json:"name"`

	// OcrContext OCR context for the event
	OcrContext string `json:"ocr_context"`

	// OcrReport OCR report for the event
	OcrReport string `json:"ocr_report"`

	// Service Service namespace for the event
	Service    string   `json:"service"`
	Signatures []string `json:"signatures"`

	// VerifiableEvent Base64 encoded verifiable event
	VerifiableEvent string `json:"verifiable_event"`
}

// CreateListener defines model for CreateListener.
type CreateListener struct {
	// Address Smart contract address to listen for events
	Address string `json:"address"`

	// Name Name of the event to listen for
	Name    string             `json:"name"`
	Options *map[string]string `json:"options,omitempty"`

	// Service Service namespace for the listener
	Service string `json:"service"`
}

// CreateOperation defines model for CreateOperation.
type CreateOperation struct {
	// Account Onchain account address performing the operation
	Account string `json:"account"`

	// AccountOperationId Unique account operation identifier
	AccountOperationId string `json:"account_operation_id"`

	// ChainId The id that identifies the chain where the account performing the operation lives
	ChainId int `json:"chain_id"`

	// Signature EIP-712 signature of the operation
	Signature    string               `json:"signature"`
	Transactions []TransactionRequest `json:"transactions"`
}

// Event defines model for Event.
type Event struct {
	// CreatedAt Timestamp of when the event was created
	CreatedAt int64 `json:"created_at"`

	// EventId Unique identifier for the event
	EventId openapi_types.UUID `json:"event_id"`

	// Name Name of the event
	Name string `json:"name"`

	// OcrContext OCR context for the event
	OcrContext string `json:"ocr_context"`

	// OcrReport OCR report for the event
	OcrReport string `json:"ocr_report"`

	// Service Service namespace for the event
	Service    string   `json:"service"`
	Signatures []string `json:"signatures"`

	// VerifiableEvent Base64 encoded verifiable event
	VerifiableEvent string `json:"verifiable_event"`
}

// EventList defines model for EventList.
type EventList struct {
	Data []Event `json:"data"`

	// HasMore True if there are more events to fetch
	HasMore bool `json:"has_more"`
}

// HealthCheck defines model for HealthCheck.
type HealthCheck struct {
	Status string `json:"status"`
}

// Listener defines model for Listener.
type Listener struct {
	// Address Smart contract address to listen for events
	Address string `json:"address"`

	// CreatedAt Timestamp of when the listener was created
	CreatedAt int64 `json:"created_at"`

	// ListenerId Unique identifier for the listener
	ListenerId openapi_types.UUID `json:"listener_id"`

	// Name Name of the event to listen for
	Name    string            `json:"name"`
	Options map[string]string `json:"options"`

	// Service Service namespace for the listener
	Service string `json:"service"`

	// Status Current status of the listener
	Status string `json:"status"`
}

// ListenerList defines model for ListenerList.
type ListenerList struct {
	Data []Listener `json:"data"`

	// HasMore True if there are more listeners to fetch
	HasMore bool `json:"has_more"`
}

// Operation defines model for Operation.
type Operation struct {
	// Account Onchain account address performing the operation
	Account string `json:"account"`

	// AccountId Identifier of the account performing the operation
	AccountId openapi_types.UUID `json:"account_id"`

	// AccountOperationId Unique account operation identifier
	AccountOperationId string `json:"account_operation_id"`

	// ChainId The id that identifies the chain where the account performing the operation lives
	ChainId int `json:"chain_id"`

	// ConfirmedAt Timestamp of when the operation was confirmed
	ConfirmedAt *int64 `json:"confirmed_at,omitempty"`

	// CreatedAt Timestamp of when the operation was created
	CreatedAt int64 `json:"created_at"`

	// OperationId Unique identifier for the operation
	OperationId openapi_types.UUID `json:"operation_id"`

	// Signature EIP-712 signature of the operation
	Signature string `json:"signature"`

	// Status Current status of the operation
	Status string `json:"status"`

	// TransactionHash Onchain transaction hash which included the operation
	TransactionHash *string       `json:"transaction_hash,omitempty"`
	Transactions    []Transaction `json:"transactions"`
}

// OperationList defines model for OperationList.
type OperationList struct {
	Data []Operation `json:"data"`

	// HasMore True if there are more operations to fetch
	HasMore bool `json:"has_more"`
}

// Transaction defines model for Transaction.
type Transaction struct {
	// Data Hex-encoded calldata for the transaction
	Data string `json:"data"`

	// To Address receiving the transaction
	To string `json:"to"`

	// Value Amount of native token value being sent in the transaction
	Value string `json:"value"`
}

// TransactionRequest defines model for TransactionRequest.
type TransactionRequest struct {
	// Data Hex-encoded calldata for the transaction
	Data string `json:"data"`

	// To Address receiving the transaction
	To string `json:"to"`

	// Value Amount of native token value being sent in the transaction
	Value string `json:"value"`
}

// UpdateOperationStatus defines model for UpdateOperationStatus.
type UpdateOperationStatus struct {
	// Account Onchain account address performing the operation
	Account string `json:"account"`

	// AccountOperationId Unique account operation identifier
	AccountOperationId string `json:"account_operation_id"`

	// ChainId The id that identifies the chain where the account performing the operation lives
	ChainId int `json:"chain_id"`

	// TransactionHash Onchain transaction hash which included the operation
	TransactionHash string `json:"transaction_hash"`

	// TransactionTimestamp Timestamp of onchain transaction which included the operation
	TransactionTimestamp int `json:"transaction_timestamp"`
}

// GetEventsParams defines parameters for GetEvents.
type GetEventsParams struct {
	// CreatedLt Filter events created before this timestamp
	CreatedLt *int64 `form:"created.lt,omitempty" json:"created.lt,omitempty"`

	// CreatedLte Filter events created at or before this timestamp
	CreatedLte *int64 `form:"created.lte,omitempty" json:"created.lte,omitempty"`

	// CreatedGt Filter events created after this timestamp
	CreatedGt *int64 `form:"created.gt,omitempty" json:"created.gt,omitempty"`

	// CreatedGte Filter events created at or after this timestamp
	CreatedGte *int64 `form:"created.gte,omitempty" json:"created.gte,omitempty"`

	// Limit The number of events to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// StartingAfter Return events starting after this event UUID
	StartingAfter *openapi_types.UUID `form:"starting_after,omitempty" json:"starting_after,omitempty"`

	// EndingBefore Return events occurring before this event UUID
	EndingBefore *openapi_types.UUID `form:"ending_before,omitempty" json:"ending_before,omitempty"`
}

// GetListenersParams defines parameters for GetListeners.
type GetListenersParams struct {
	// CreatedLt Filter events created before this timestamp
	CreatedLt *int64 `form:"created.lt,omitempty" json:"created.lt,omitempty"`

	// CreatedLte Filter events created at or before this timestamp
	CreatedLte *int64 `form:"created.lte,omitempty" json:"created.lte,omitempty"`

	// CreatedGt Filter events created after this timestamp
	CreatedGt *int64 `form:"created.gt,omitempty" json:"created.gt,omitempty"`

	// CreatedGte Filter events created at or after this timestamp
	CreatedGte *int64 `form:"created.gte,omitempty" json:"created.gte,omitempty"`

	// Limit The number of events to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// StartingAfter Return events starting after this event UUID
	StartingAfter *openapi_types.UUID `form:"starting_after,omitempty" json:"starting_after,omitempty"`

	// EndingBefore Return events occurring before this event UUID
	EndingBefore *openapi_types.UUID `form:"ending_before,omitempty" json:"ending_before,omitempty"`
}

// GetOperationsParams defines parameters for GetOperations.
type GetOperationsParams struct {
	// CreatedLt Filter operations created before this timestamp
	CreatedLt *int64 `form:"created.lt,omitempty" json:"created.lt,omitempty"`

	// CreatedLte Filter operations created at or before this timestamp
	CreatedLte *int64 `form:"created.lte,omitempty" json:"created.lte,omitempty"`

	// CreatedGt Filter operations created after this timestamp
	CreatedGt *int64 `form:"created.gt,omitempty" json:"created.gt,omitempty"`

	// CreatedGte Filter operations created at or after this timestamp
	CreatedGte *int64 `form:"created.gte,omitempty" json:"created.gte,omitempty"`

	// Limit The number of operations to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// StartingAfter Return operations starting after this operation UUID
	StartingAfter *openapi_types.UUID `form:"starting_after,omitempty" json:"starting_after,omitempty"`

	// EndingBefore Return operations occurring before this operation UUID
	EndingBefore *openapi_types.UUID `form:"ending_before,omitempty" json:"ending_before,omitempty"`
}

// PostEventsJSONRequestBody defines body for PostEvents for application/json ContentType.
type PostEventsJSONRequestBody = CreateEvent

// PostListenersJSONRequestBody defines body for PostListeners for application/json ContentType.
type PostListenersJSONRequestBody = CreateListener

// PostOperationStatusJSONRequestBody defines body for PostOperationStatus for application/json ContentType.
type PostOperationStatusJSONRequestBody = UpdateOperationStatus

// PostOperationsJSONRequestBody defines body for PostOperations for application/json ContentType.
type PostOperationsJSONRequestBody = CreateOperation

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetEvents request
	GetEvents(ctx context.Context, params *GetEventsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostEventsWithBody request with any body
	PostEventsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostEvents(ctx context.Context, body PostEventsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealthCheck request
	GetHealthCheck(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetListeners request
	GetListeners(ctx context.Context, params *GetListenersParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostListenersWithBody request with any body
	PostListenersWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostListeners(ctx context.Context, body PostListenersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostOperationStatusWithBody request with any body
	PostOperationStatusWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostOperationStatus(ctx context.Context, body PostOperationStatusJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetOperations request
	GetOperations(ctx context.Context, params *GetOperationsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostOperationsWithBody request with any body
	PostOperationsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostOperations(ctx context.Context, body PostOperationsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetOperationsOperationId request
	GetOperationsOperationId(ctx context.Context, operationId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetEvents(ctx context.Context, params *GetEventsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetEventsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostEventsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostEventsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostEvents(ctx context.Context, body PostEventsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostEventsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHealthCheck(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthCheckRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetListeners(ctx context.Context, params *GetListenersParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetListenersRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostListenersWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostListenersRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostListeners(ctx context.Context, body PostListenersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostListenersRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostOperationStatusWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostOperationStatusRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostOperationStatus(ctx context.Context, body PostOperationStatusJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostOperationStatusRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetOperations(ctx context.Context, params *GetOperationsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetOperationsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostOperationsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostOperationsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostOperations(ctx context.Context, body PostOperationsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostOperationsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetOperationsOperationId(ctx context.Context, operationId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetOperationsOperationIdRequest(c.Server, operationId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetEventsRequest generates requests for GetEvents
func NewGetEventsRequest(server string, params *GetEventsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/events")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.CreatedLt != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "created.lt", runtime.ParamLocationQuery, *params.CreatedLt); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.CreatedLte != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "created.lte", runtime.ParamLocationQuery, *params.CreatedLte); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.CreatedGt != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "created.gt", runtime.ParamLocationQuery, *params.CreatedGt); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.CreatedGte != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "created.gte", runtime.ParamLocationQuery, *params.CreatedGte); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.StartingAfter != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "starting_after", runtime.ParamLocationQuery, *params.StartingAfter); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.EndingBefore != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "ending_before", runtime.ParamLocationQuery, *params.EndingBefore); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostEventsRequest calls the generic PostEvents builder with application/json body
func NewPostEventsRequest(server string, body PostEventsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostEventsRequestWithBody(server, "application/json", bodyReader)
}

// NewPostEventsRequestWithBody generates requests for PostEvents with any type of body
func NewPostEventsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/events")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetHealthCheckRequest generates requests for GetHealthCheck
func NewGetHealthCheckRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health-check")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetListenersRequest generates requests for GetListeners
func NewGetListenersRequest(server string, params *GetListenersParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/listeners")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.CreatedLt != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "created.lt", runtime.ParamLocationQuery, *params.CreatedLt); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.CreatedLte != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "created.lte", runtime.ParamLocationQuery, *params.CreatedLte); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.CreatedGt != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "created.gt", runtime.ParamLocationQuery, *params.CreatedGt); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.CreatedGte != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "created.gte", runtime.ParamLocationQuery, *params.CreatedGte); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.StartingAfter != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "starting_after", runtime.ParamLocationQuery, *params.StartingAfter); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.EndingBefore != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "ending_before", runtime.ParamLocationQuery, *params.EndingBefore); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostListenersRequest calls the generic PostListeners builder with application/json body
func NewPostListenersRequest(server string, body PostListenersJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostListenersRequestWithBody(server, "application/json", bodyReader)
}

// NewPostListenersRequestWithBody generates requests for PostListeners with any type of body
func NewPostListenersRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/listeners")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostOperationStatusRequest calls the generic PostOperationStatus builder with application/json body
func NewPostOperationStatusRequest(server string, body PostOperationStatusJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostOperationStatusRequestWithBody(server, "application/json", bodyReader)
}

// NewPostOperationStatusRequestWithBody generates requests for PostOperationStatus with any type of body
func NewPostOperationStatusRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/operation_status")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetOperationsRequest generates requests for GetOperations
func NewGetOperationsRequest(server string, params *GetOperationsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/operations")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.CreatedLt != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "created.lt", runtime.ParamLocationQuery, *params.CreatedLt); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.CreatedLte != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "created.lte", runtime.ParamLocationQuery, *params.CreatedLte); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.CreatedGt != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "created.gt", runtime.ParamLocationQuery, *params.CreatedGt); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.CreatedGte != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "created.gte", runtime.ParamLocationQuery, *params.CreatedGte); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.StartingAfter != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "starting_after", runtime.ParamLocationQuery, *params.StartingAfter); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.EndingBefore != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "ending_before", runtime.ParamLocationQuery, *params.EndingBefore); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostOperationsRequest calls the generic PostOperations builder with application/json body
func NewPostOperationsRequest(server string, body PostOperationsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostOperationsRequestWithBody(server, "application/json", bodyReader)
}

// NewPostOperationsRequestWithBody generates requests for PostOperations with any type of body
func NewPostOperationsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/operations")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetOperationsOperationIdRequest generates requests for GetOperationsOperationId
func NewGetOperationsOperationIdRequest(server string, operationId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "operation_id", runtime.ParamLocationPath, operationId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/operations/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetEventsWithResponse request
	GetEventsWithResponse(ctx context.Context, params *GetEventsParams, reqEditors ...RequestEditorFn) (*GetEventsResponse, error)

	// PostEventsWithBodyWithResponse request with any body
	PostEventsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostEventsResponse, error)

	PostEventsWithResponse(ctx context.Context, body PostEventsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostEventsResponse, error)

	// GetHealthCheckWithResponse request
	GetHealthCheckWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthCheckResponse, error)

	// GetListenersWithResponse request
	GetListenersWithResponse(ctx context.Context, params *GetListenersParams, reqEditors ...RequestEditorFn) (*GetListenersResponse, error)

	// PostListenersWithBodyWithResponse request with any body
	PostListenersWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostListenersResponse, error)

	PostListenersWithResponse(ctx context.Context, body PostListenersJSONRequestBody, reqEditors ...RequestEditorFn) (*PostListenersResponse, error)

	// PostOperationStatusWithBodyWithResponse request with any body
	PostOperationStatusWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostOperationStatusResponse, error)

	PostOperationStatusWithResponse(ctx context.Context, body PostOperationStatusJSONRequestBody, reqEditors ...RequestEditorFn) (*PostOperationStatusResponse, error)

	// GetOperationsWithResponse request
	GetOperationsWithResponse(ctx context.Context, params *GetOperationsParams, reqEditors ...RequestEditorFn) (*GetOperationsResponse, error)

	// PostOperationsWithBodyWithResponse request with any body
	PostOperationsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostOperationsResponse, error)

	PostOperationsWithResponse(ctx context.Context, body PostOperationsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostOperationsResponse, error)

	// GetOperationsOperationIdWithResponse request
	GetOperationsOperationIdWithResponse(ctx context.Context, operationId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetOperationsOperationIdResponse, error)
}

type GetEventsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EventList
}

// Status returns HTTPResponse.Status
func (r GetEventsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetEventsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostEventsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Event
}

// Status returns HTTPResponse.Status
func (r PostEventsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostEventsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHealthCheckResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HealthCheck
}

// Status returns HTTPResponse.Status
func (r GetHealthCheckResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthCheckResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetListenersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListenerList
}

// Status returns HTTPResponse.Status
func (r GetListenersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetListenersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostListenersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Listener
}

// Status returns HTTPResponse.Status
func (r PostListenersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostListenersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostOperationStatusResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostOperationStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostOperationStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetOperationsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *OperationList
}

// Status returns HTTPResponse.Status
func (r GetOperationsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetOperationsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostOperationsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Operation
}

// Status returns HTTPResponse.Status
func (r PostOperationsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostOperationsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetOperationsOperationIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Operation
}

// Status returns HTTPResponse.Status
func (r GetOperationsOperationIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetOperationsOperationIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetEventsWithResponse request returning *GetEventsResponse
func (c *ClientWithResponses) GetEventsWithResponse(ctx context.Context, params *GetEventsParams, reqEditors ...RequestEditorFn) (*GetEventsResponse, error) {
	rsp, err := c.GetEvents(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetEventsResponse(rsp)
}

// PostEventsWithBodyWithResponse request with arbitrary body returning *PostEventsResponse
func (c *ClientWithResponses) PostEventsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostEventsResponse, error) {
	rsp, err := c.PostEventsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostEventsResponse(rsp)
}

func (c *ClientWithResponses) PostEventsWithResponse(ctx context.Context, body PostEventsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostEventsResponse, error) {
	rsp, err := c.PostEvents(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostEventsResponse(rsp)
}

// GetHealthCheckWithResponse request returning *GetHealthCheckResponse
func (c *ClientWithResponses) GetHealthCheckWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthCheckResponse, error) {
	rsp, err := c.GetHealthCheck(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthCheckResponse(rsp)
}

// GetListenersWithResponse request returning *GetListenersResponse
func (c *ClientWithResponses) GetListenersWithResponse(ctx context.Context, params *GetListenersParams, reqEditors ...RequestEditorFn) (*GetListenersResponse, error) {
	rsp, err := c.GetListeners(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetListenersResponse(rsp)
}

// PostListenersWithBodyWithResponse request with arbitrary body returning *PostListenersResponse
func (c *ClientWithResponses) PostListenersWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostListenersResponse, error) {
	rsp, err := c.PostListenersWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostListenersResponse(rsp)
}

func (c *ClientWithResponses) PostListenersWithResponse(ctx context.Context, body PostListenersJSONRequestBody, reqEditors ...RequestEditorFn) (*PostListenersResponse, error) {
	rsp, err := c.PostListeners(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostListenersResponse(rsp)
}

// PostOperationStatusWithBodyWithResponse request with arbitrary body returning *PostOperationStatusResponse
func (c *ClientWithResponses) PostOperationStatusWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostOperationStatusResponse, error) {
	rsp, err := c.PostOperationStatusWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostOperationStatusResponse(rsp)
}

func (c *ClientWithResponses) PostOperationStatusWithResponse(ctx context.Context, body PostOperationStatusJSONRequestBody, reqEditors ...RequestEditorFn) (*PostOperationStatusResponse, error) {
	rsp, err := c.PostOperationStatus(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostOperationStatusResponse(rsp)
}

// GetOperationsWithResponse request returning *GetOperationsResponse
func (c *ClientWithResponses) GetOperationsWithResponse(ctx context.Context, params *GetOperationsParams, reqEditors ...RequestEditorFn) (*GetOperationsResponse, error) {
	rsp, err := c.GetOperations(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetOperationsResponse(rsp)
}

// PostOperationsWithBodyWithResponse request with arbitrary body returning *PostOperationsResponse
func (c *ClientWithResponses) PostOperationsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostOperationsResponse, error) {
	rsp, err := c.PostOperationsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostOperationsResponse(rsp)
}

func (c *ClientWithResponses) PostOperationsWithResponse(ctx context.Context, body PostOperationsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostOperationsResponse, error) {
	rsp, err := c.PostOperations(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostOperationsResponse(rsp)
}

// GetOperationsOperationIdWithResponse request returning *GetOperationsOperationIdResponse
func (c *ClientWithResponses) GetOperationsOperationIdWithResponse(ctx context.Context, operationId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetOperationsOperationIdResponse, error) {
	rsp, err := c.GetOperationsOperationId(ctx, operationId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetOperationsOperationIdResponse(rsp)
}

// ParseGetEventsResponse parses an HTTP response from a GetEventsWithResponse call
func ParseGetEventsResponse(rsp *http.Response) (*GetEventsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetEventsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EventList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostEventsResponse parses an HTTP response from a PostEventsWithResponse call
func ParsePostEventsResponse(rsp *http.Response) (*PostEventsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostEventsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Event
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParseGetHealthCheckResponse parses an HTTP response from a GetHealthCheckWithResponse call
func ParseGetHealthCheckResponse(rsp *http.Response) (*GetHealthCheckResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthCheckResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthCheck
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetListenersResponse parses an HTTP response from a GetListenersWithResponse call
func ParseGetListenersResponse(rsp *http.Response) (*GetListenersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetListenersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListenerList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostListenersResponse parses an HTTP response from a PostListenersWithResponse call
func ParsePostListenersResponse(rsp *http.Response) (*PostListenersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostListenersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Listener
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParsePostOperationStatusResponse parses an HTTP response from a PostOperationStatusWithResponse call
func ParsePostOperationStatusResponse(rsp *http.Response) (*PostOperationStatusResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostOperationStatusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetOperationsResponse parses an HTTP response from a GetOperationsWithResponse call
func ParseGetOperationsResponse(rsp *http.Response) (*GetOperationsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetOperationsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest OperationList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostOperationsResponse parses an HTTP response from a PostOperationsWithResponse call
func ParsePostOperationsResponse(rsp *http.Response) (*PostOperationsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostOperationsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Operation
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParseGetOperationsOperationIdResponse parses an HTTP response from a GetOperationsOperationIdWithResponse call
func ParseGetOperationsOperationIdResponse(rsp *http.Response) (*GetOperationsOperationIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetOperationsOperationIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Operation
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
