// Code generated by genaliases; DO NOT EDIT.
package client

import cvnapi "github.com/smartcontractkit/cvn-api-go/client"

type (
	Account                           = cvnapi.Account
	AccountList                       = cvnapi.AccountList
	ApplicationError                  = cvnapi.ApplicationError
	ApplicationErrorType              = cvnapi.ApplicationErrorType
	Client                            = cvnapi.Client
	ClientInterface                   = cvnapi.ClientInterface
	ClientWithResponses               = cvnapi.ClientWithResponses
	ClientWithResponsesInterface      = cvnapi.ClientWithResponsesInterface
	CreateAccount                     = cvnapi.CreateAccount
	CreateEvent                       = cvnapi.CreateEvent
	CreateListener                    = cvnapi.CreateListener
	CreateOperation                   = cvnapi.CreateOperation
	DeleteListenersListenerIdResponse = cvnapi.DeleteListenersListenerIdResponse
	Event                             = cvnapi.Event
	EventList                         = cvnapi.EventList
	GetAccountsAccountIdResponse      = cvnapi.GetAccountsAccountIdResponse
	GetAccountsParams                 = cvnapi.GetAccountsParams
	GetAccountsResponse               = cvnapi.GetAccountsResponse
	GetEventsEventIdResponse          = cvnapi.GetEventsEventIdResponse
	GetEventsParams                   = cvnapi.GetEventsParams
	GetEventsResponse                 = cvnapi.GetEventsResponse
	GetHealthCheckResponse            = cvnapi.GetHealthCheckResponse
	GetListenersListenerIdResponse    = cvnapi.GetListenersListenerIdResponse
	GetListenersParams                = cvnapi.GetListenersParams
	GetListenersResponse              = cvnapi.GetListenersResponse
	GetOperationsOperationIdResponse  = cvnapi.GetOperationsOperationIdResponse
	GetOperationsParams               = cvnapi.GetOperationsParams
	GetOperationsResponse             = cvnapi.GetOperationsResponse
	HealthCheck                       = cvnapi.HealthCheck
	HttpRequestDoer                   = cvnapi.HttpRequestDoer
	Listener                          = cvnapi.Listener
	ListenerList                      = cvnapi.ListenerList
	Operation                         = cvnapi.Operation
	OperationList                     = cvnapi.OperationList
	PostAccountsResponse              = cvnapi.PostAccountsResponse
	PostEventsResponse                = cvnapi.PostEventsResponse
	PostListenersResponse             = cvnapi.PostListenersResponse
	PostOperationStatusResponse       = cvnapi.PostOperationStatusResponse
	PostOperationsResponse            = cvnapi.PostOperationsResponse
	Transaction                       = cvnapi.Transaction
	TransactionRequest                = cvnapi.TransactionRequest
	UpdateOperationStatus             = cvnapi.UpdateOperationStatus
)

const (
	AlreadyExists    ApplicationErrorType = cvnapi.AlreadyExists
	ApiKeyAuthScopes                      = cvnapi.ApiKeyAuthScopes
	BadRequest       ApplicationErrorType = cvnapi.BadRequest
	InternalError    ApplicationErrorType = cvnapi.InternalError
	NotFound         ApplicationErrorType = cvnapi.NotFound
)
