//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"context"
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// CreateEvent defines model for CreateEvent.
type CreateEvent struct {
	// Address Smart contract address from which the event was emitted
	Address string `json:"address"`

	// ChainId The id that identifies the chain where the event happened
	ChainId string `json:"chain_id"`

	// Name Name of the event
	Name string `json:"name"`

	// OcrContext OCR context for the event
	OcrContext string `json:"ocr_context"`

	// OcrReport OCR report for the event
	OcrReport string `json:"ocr_report"`

	// Service Service namespace for the event
	Service    string   `json:"service"`
	Signatures []string `json:"signatures"`

	// VerifiableEvent Base64 encoded verifiable event
	VerifiableEvent string `json:"verifiable_event"`
}

// CreateListener defines model for CreateListener.
type CreateListener struct {
	// Address Smart contract address to listen for events
	Address string `json:"address"`

	// ChainId The id that identifies the chain where the listener will run
	ChainId string `json:"chain_id"`

	// Name Name of the event to listen for
	Name    string             `json:"name"`
	Options *map[string]string `json:"options,omitempty"`

	// Service Service namespace for the listener
	Service string `json:"service"`
}

// CreateOperation defines model for CreateOperation.
type CreateOperation struct {
	// Account Onchain account address performing the operation
	Account string `json:"account"`

	// AccountOperationId Unique account operation identifier
	AccountOperationId string `json:"account_operation_id"`

	// ChainId The id that identifies the chain where the account performing the operation lives
	ChainId string `json:"chain_id"`

	// Signature EIP-712 signature of the operation
	Signature    string               `json:"signature"`
	Transactions []TransactionRequest `json:"transactions"`
}

// Event defines model for Event.
type Event struct {
	// Address The address of the smart contract from which the event was emitted
	Address string `json:"address"`

	// ChainId The id that identifies the chain where the event happened
	ChainId string `json:"chain_id"`

	// CreatedAt Timestamp of when the event was created
	CreatedAt int64 `json:"created_at"`

	// EventId Unique identifier for the event
	EventId openapi_types.UUID `json:"event_id"`

	// Name Name of the event
	Name string `json:"name"`

	// OcrContext OCR context for the event
	OcrContext string `json:"ocr_context"`

	// OcrReport OCR report for the event
	OcrReport string `json:"ocr_report"`

	// Service Service namespace for the event
	Service    string   `json:"service"`
	Signatures []string `json:"signatures"`

	// VerifiableEvent Base64 encoded verifiable event
	VerifiableEvent string `json:"verifiable_event"`
}

// EventList defines model for EventList.
type EventList struct {
	Data []Event `json:"data"`

	// HasMore True if there are more events to fetch
	HasMore bool `json:"has_more"`
}

// HealthCheck defines model for HealthCheck.
type HealthCheck struct {
	Status string `json:"status"`
}

// Listener defines model for Listener.
type Listener struct {
	// Address Smart contract address to listen for events
	Address string `json:"address"`

	// ChainId The id that identifies the chain where the listener will run
	ChainId string `json:"chain_id"`

	// CreatedAt Timestamp of when the listener was created
	CreatedAt int64 `json:"created_at"`

	// ListenerId Unique identifier for the listener
	ListenerId openapi_types.UUID `json:"listener_id"`

	// Name Name of the event to listen for
	Name    string            `json:"name"`
	Options map[string]string `json:"options"`

	// Service Service namespace for the listener
	Service string `json:"service"`

	// Status Current status of the listener
	Status string `json:"status"`
}

// ListenerList defines model for ListenerList.
type ListenerList struct {
	Data []Listener `json:"data"`

	// HasMore True if there are more listeners to fetch
	HasMore bool `json:"has_more"`
}

// Operation defines model for Operation.
type Operation struct {
	// Account Onchain account address performing the operation
	Account string `json:"account"`

	// AccountId Identifier of the account performing the operation
	AccountId openapi_types.UUID `json:"account_id"`

	// AccountOperationId Unique account operation identifier
	AccountOperationId string `json:"account_operation_id"`

	// ChainId The id that identifies the chain where the account performing the operation lives
	ChainId string `json:"chain_id"`

	// ConfirmedAt Timestamp of when the operation was confirmed
	ConfirmedAt *int64 `json:"confirmed_at,omitempty"`

	// CreatedAt Timestamp of when the operation was created
	CreatedAt int64 `json:"created_at"`

	// OperationId Unique identifier for the operation
	OperationId openapi_types.UUID `json:"operation_id"`

	// Signature EIP-712 signature of the operation
	Signature string `json:"signature"`

	// Status Current status of the operation
	Status string `json:"status"`

	// TransactionHash Onchain transaction hash which included the operation
	TransactionHash *string       `json:"transaction_hash,omitempty"`
	Transactions    []Transaction `json:"transactions"`
}

// OperationList defines model for OperationList.
type OperationList struct {
	Data []Operation `json:"data"`

	// HasMore True if there are more operations to fetch
	HasMore bool `json:"has_more"`
}

// Transaction defines model for Transaction.
type Transaction struct {
	// Data Hex-encoded calldata for the transaction
	Data string `json:"data"`

	// To Address receiving the transaction
	To string `json:"to"`

	// Value Amount of native token value being sent in the transaction
	Value string `json:"value"`
}

// TransactionRequest defines model for TransactionRequest.
type TransactionRequest struct {
	// Data Hex-encoded calldata for the transaction
	Data string `json:"data"`

	// To Address receiving the transaction
	To string `json:"to"`

	// Value Amount of native token value being sent in the transaction
	Value string `json:"value"`
}

// UpdateOperationStatus defines model for UpdateOperationStatus.
type UpdateOperationStatus struct {
	// Account Onchain account address performing the operation
	Account string `json:"account"`

	// AccountOperationId Unique account operation identifier
	AccountOperationId string `json:"account_operation_id"`

	// ChainId The id that identifies the chain where the account performing the operation lives
	ChainId string `json:"chain_id"`

	// TransactionHash Onchain transaction hash which included the operation
	TransactionHash string `json:"transaction_hash"`

	// TransactionTimestamp Timestamp of onchain transaction which included the operation
	TransactionTimestamp int `json:"transaction_timestamp"`
}

// GetEventsParams defines parameters for GetEvents.
type GetEventsParams struct {
	// CreatedLt Filter events created before this timestamp
	CreatedLt *int64 `form:"created.lt,omitempty" json:"created.lt,omitempty"`

	// CreatedLte Filter events created at or before this timestamp
	CreatedLte *int64 `form:"created.lte,omitempty" json:"created.lte,omitempty"`

	// CreatedGt Filter events created after this timestamp
	CreatedGt *int64 `form:"created.gt,omitempty" json:"created.gt,omitempty"`

	// CreatedGte Filter events created at or after this timestamp
	CreatedGte *int64 `form:"created.gte,omitempty" json:"created.gte,omitempty"`

	// Limit The number of events to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// StartingAfter Return events starting after this event UUID
	StartingAfter *openapi_types.UUID `form:"starting_after,omitempty" json:"starting_after,omitempty"`

	// EndingBefore Return events occurring before this event UUID
	EndingBefore *openapi_types.UUID `form:"ending_before,omitempty" json:"ending_before,omitempty"`
}

// GetListenersParams defines parameters for GetListeners.
type GetListenersParams struct {
	// CreatedLt Filter events created before this timestamp
	CreatedLt *int64 `form:"created.lt,omitempty" json:"created.lt,omitempty"`

	// CreatedLte Filter events created at or before this timestamp
	CreatedLte *int64 `form:"created.lte,omitempty" json:"created.lte,omitempty"`

	// CreatedGt Filter events created after this timestamp
	CreatedGt *int64 `form:"created.gt,omitempty" json:"created.gt,omitempty"`

	// CreatedGte Filter events created at or after this timestamp
	CreatedGte *int64 `form:"created.gte,omitempty" json:"created.gte,omitempty"`

	// Limit The number of events to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// StartingAfter Return events starting after this event UUID
	StartingAfter *openapi_types.UUID `form:"starting_after,omitempty" json:"starting_after,omitempty"`

	// EndingBefore Return events occurring before this event UUID
	EndingBefore *openapi_types.UUID `form:"ending_before,omitempty" json:"ending_before,omitempty"`
}

// GetOperationsParams defines parameters for GetOperations.
type GetOperationsParams struct {
	// CreatedLt Filter operations created before this timestamp
	CreatedLt *int64 `form:"created.lt,omitempty" json:"created.lt,omitempty"`

	// CreatedLte Filter operations created at or before this timestamp
	CreatedLte *int64 `form:"created.lte,omitempty" json:"created.lte,omitempty"`

	// CreatedGt Filter operations created after this timestamp
	CreatedGt *int64 `form:"created.gt,omitempty" json:"created.gt,omitempty"`

	// CreatedGte Filter operations created at or after this timestamp
	CreatedGte *int64 `form:"created.gte,omitempty" json:"created.gte,omitempty"`

	// Limit The number of operations to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// StartingAfter Return operations starting after this operation UUID
	StartingAfter *openapi_types.UUID `form:"starting_after,omitempty" json:"starting_after,omitempty"`

	// EndingBefore Return operations occurring before this operation UUID
	EndingBefore *openapi_types.UUID `form:"ending_before,omitempty" json:"ending_before,omitempty"`
}

// PostEventsJSONRequestBody defines body for PostEvents for application/json ContentType.
type PostEventsJSONRequestBody = CreateEvent

// PostListenersJSONRequestBody defines body for PostListeners for application/json ContentType.
type PostListenersJSONRequestBody = CreateListener

// PostOperationStatusJSONRequestBody defines body for PostOperationStatus for application/json ContentType.
type PostOperationStatusJSONRequestBody = UpdateOperationStatus

// PostOperationsJSONRequestBody defines body for PostOperations for application/json ContentType.
type PostOperationsJSONRequestBody = CreateOperation

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Retrieves events.
	// (GET /events)
	GetEvents(w http.ResponseWriter, r *http.Request, params GetEventsParams)
	// Creates a new event.
	// (POST /events)
	PostEvents(w http.ResponseWriter, r *http.Request)
	// Health check endpoint
	// (GET /health-check)
	GetHealthCheck(w http.ResponseWriter, r *http.Request)
	// Retrieves event listeners.
	// (GET /listeners)
	GetListeners(w http.ResponseWriter, r *http.Request, params GetListenersParams)
	// Creates a new listener.
	// (POST /listeners)
	PostListeners(w http.ResponseWriter, r *http.Request)
	// Deletes a listener.
	// (DELETE /listeners/{listener_id})
	DeleteListenersListenerId(w http.ResponseWriter, r *http.Request, listenerId openapi_types.UUID)
	// Retrieves a single listener.
	// (GET /listeners/{listener_id})
	GetListenersListenerId(w http.ResponseWriter, r *http.Request, listenerId openapi_types.UUID)
	// Updates the status of an operation.
	// (POST /operation_status)
	PostOperationStatus(w http.ResponseWriter, r *http.Request)
	// Retrieves operations.
	// (GET /operations)
	GetOperations(w http.ResponseWriter, r *http.Request, params GetOperationsParams)
	// Sends an onchain transaction.
	// (POST /operations)
	PostOperations(w http.ResponseWriter, r *http.Request)
	// Retrieves the status of an operation.
	// (GET /operations/{operation_id})
	GetOperationsOperationId(w http.ResponseWriter, r *http.Request, operationId openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetEvents operation middleware
func (siw *ServerInterfaceWrapper) GetEvents(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEventsParams

	// ------------- Optional query parameter "created.lt" -------------

	err = runtime.BindQueryParameter("form", true, false, "created.lt", r.URL.Query(), &params.CreatedLt)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created.lt", Err: err})
		return
	}

	// ------------- Optional query parameter "created.lte" -------------

	err = runtime.BindQueryParameter("form", true, false, "created.lte", r.URL.Query(), &params.CreatedLte)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created.lte", Err: err})
		return
	}

	// ------------- Optional query parameter "created.gt" -------------

	err = runtime.BindQueryParameter("form", true, false, "created.gt", r.URL.Query(), &params.CreatedGt)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created.gt", Err: err})
		return
	}

	// ------------- Optional query parameter "created.gte" -------------

	err = runtime.BindQueryParameter("form", true, false, "created.gte", r.URL.Query(), &params.CreatedGte)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created.gte", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "starting_after" -------------

	err = runtime.BindQueryParameter("form", true, false, "starting_after", r.URL.Query(), &params.StartingAfter)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "starting_after", Err: err})
		return
	}

	// ------------- Optional query parameter "ending_before" -------------

	err = runtime.BindQueryParameter("form", true, false, "ending_before", r.URL.Query(), &params.EndingBefore)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ending_before", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostEvents operation middleware
func (siw *ServerInterfaceWrapper) PostEvents(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEvents(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthCheck operation middleware
func (siw *ServerInterfaceWrapper) GetHealthCheck(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetListeners operation middleware
func (siw *ServerInterfaceWrapper) GetListeners(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetListenersParams

	// ------------- Optional query parameter "created.lt" -------------

	err = runtime.BindQueryParameter("form", true, false, "created.lt", r.URL.Query(), &params.CreatedLt)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created.lt", Err: err})
		return
	}

	// ------------- Optional query parameter "created.lte" -------------

	err = runtime.BindQueryParameter("form", true, false, "created.lte", r.URL.Query(), &params.CreatedLte)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created.lte", Err: err})
		return
	}

	// ------------- Optional query parameter "created.gt" -------------

	err = runtime.BindQueryParameter("form", true, false, "created.gt", r.URL.Query(), &params.CreatedGt)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created.gt", Err: err})
		return
	}

	// ------------- Optional query parameter "created.gte" -------------

	err = runtime.BindQueryParameter("form", true, false, "created.gte", r.URL.Query(), &params.CreatedGte)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created.gte", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "starting_after" -------------

	err = runtime.BindQueryParameter("form", true, false, "starting_after", r.URL.Query(), &params.StartingAfter)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "starting_after", Err: err})
		return
	}

	// ------------- Optional query parameter "ending_before" -------------

	err = runtime.BindQueryParameter("form", true, false, "ending_before", r.URL.Query(), &params.EndingBefore)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ending_before", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetListeners(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostListeners operation middleware
func (siw *ServerInterfaceWrapper) PostListeners(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostListeners(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteListenersListenerId operation middleware
func (siw *ServerInterfaceWrapper) DeleteListenersListenerId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "listener_id" -------------
	var listenerId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "listener_id", r.PathValue("listener_id"), &listenerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "listener_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteListenersListenerId(w, r, listenerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetListenersListenerId operation middleware
func (siw *ServerInterfaceWrapper) GetListenersListenerId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "listener_id" -------------
	var listenerId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "listener_id", r.PathValue("listener_id"), &listenerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "listener_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetListenersListenerId(w, r, listenerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostOperationStatus operation middleware
func (siw *ServerInterfaceWrapper) PostOperationStatus(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostOperationStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOperations operation middleware
func (siw *ServerInterfaceWrapper) GetOperations(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetOperationsParams

	// ------------- Optional query parameter "created.lt" -------------

	err = runtime.BindQueryParameter("form", true, false, "created.lt", r.URL.Query(), &params.CreatedLt)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created.lt", Err: err})
		return
	}

	// ------------- Optional query parameter "created.lte" -------------

	err = runtime.BindQueryParameter("form", true, false, "created.lte", r.URL.Query(), &params.CreatedLte)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created.lte", Err: err})
		return
	}

	// ------------- Optional query parameter "created.gt" -------------

	err = runtime.BindQueryParameter("form", true, false, "created.gt", r.URL.Query(), &params.CreatedGt)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created.gt", Err: err})
		return
	}

	// ------------- Optional query parameter "created.gte" -------------

	err = runtime.BindQueryParameter("form", true, false, "created.gte", r.URL.Query(), &params.CreatedGte)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created.gte", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "starting_after" -------------

	err = runtime.BindQueryParameter("form", true, false, "starting_after", r.URL.Query(), &params.StartingAfter)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "starting_after", Err: err})
		return
	}

	// ------------- Optional query parameter "ending_before" -------------

	err = runtime.BindQueryParameter("form", true, false, "ending_before", r.URL.Query(), &params.EndingBefore)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ending_before", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOperations(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostOperations operation middleware
func (siw *ServerInterfaceWrapper) PostOperations(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostOperations(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOperationsOperationId operation middleware
func (siw *ServerInterfaceWrapper) GetOperationsOperationId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "operation_id" -------------
	var operationId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "operation_id", r.PathValue("operation_id"), &operationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "operation_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOperationsOperationId(w, r, operationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/events", wrapper.GetEvents)
	m.HandleFunc("POST "+options.BaseURL+"/events", wrapper.PostEvents)
	m.HandleFunc("GET "+options.BaseURL+"/health-check", wrapper.GetHealthCheck)
	m.HandleFunc("GET "+options.BaseURL+"/listeners", wrapper.GetListeners)
	m.HandleFunc("POST "+options.BaseURL+"/listeners", wrapper.PostListeners)
	m.HandleFunc("DELETE "+options.BaseURL+"/listeners/{listener_id}", wrapper.DeleteListenersListenerId)
	m.HandleFunc("GET "+options.BaseURL+"/listeners/{listener_id}", wrapper.GetListenersListenerId)
	m.HandleFunc("POST "+options.BaseURL+"/operation_status", wrapper.PostOperationStatus)
	m.HandleFunc("GET "+options.BaseURL+"/operations", wrapper.GetOperations)
	m.HandleFunc("POST "+options.BaseURL+"/operations", wrapper.PostOperations)
	m.HandleFunc("GET "+options.BaseURL+"/operations/{operation_id}", wrapper.GetOperationsOperationId)

	return m
}
