//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ArrayOfEvents defines model for ArrayOfEvents.
type ArrayOfEvents = []Event

// ArrayOfOperations defines model for ArrayOfOperations.
type ArrayOfOperations = []Operation

// Event defines model for Event.
type Event struct {
	// CreatedAt Timestamp of when the event was created
	CreatedAt *int64 `json:"created_at,omitempty"`

	// EventId Unique identifier for the event
	EventId *openapi_types.UUID `json:"event_id,omitempty"`

	// Name Name of the event
	Name *string `json:"name,omitempty"`

	// OcrContext OCR context associated with the event
	OcrContext *string `json:"ocr_context,omitempty"`

	// OcrReport OCR report associated with the event
	OcrReport *string `json:"ocr_report,omitempty"`

	// Service Service namespace for the event
	Service    *string   `json:"service,omitempty"`
	Signatures *[]string `json:"signatures,omitempty"`

	// VerifiableEvent Base64 encoded verifiable event
	VerifiableEvent *string `json:"verifiable_event,omitempty"`
}

// EventRequest defines model for EventRequest.
type EventRequest struct {
	// Address Smart contract address from which the event was emitted
	Address string `json:"address"`

	// Name Name of the event
	Name string `json:"name"`

	// OcrContext OCR context associated with the event
	OcrContext string `json:"ocr_context"`

	// OcrReport OCR report associated with the event
	OcrReport string `json:"ocr_report"`

	// Service Service namespace for the event
	Service    string   `json:"service"`
	Signatures []string `json:"signatures"`

	// VerifiableEvent Base64 encoded verifiable event
	VerifiableEvent string `json:"verifiable_event"`
}

// EventResponse defines model for EventResponse.
type EventResponse struct {
	Data *ArrayOfEvents `json:"data,omitempty"`

	// HasMore True if there are more events to fetch
	HasMore *bool `json:"has_more,omitempty"`
}

// ListenerRequest defines model for ListenerRequest.
type ListenerRequest struct {
	// Address Smart contract address to listen for events
	Address string `json:"address"`

	// Name Name of the event to listen for
	Name    string             `json:"name"`
	Options *map[string]string `json:"options,omitempty"`

	// Service Service namespace for the listener
	Service string `json:"service"`
}

// Operation defines model for Operation.
type Operation struct {
	// Account Onchain account address performing the operation
	Account *string `json:"account,omitempty"`

	// AccountOperationId Unique account operation identifier
	AccountOperationId *string `json:"account_operation_id,omitempty"`

	// CreatedAt Timestamp of when the operation was created
	CreatedAt *int `json:"created_at,omitempty"`

	// OperationId Unique identifier for the operation
	OperationId *openapi_types.UUID `json:"operation_id,omitempty"`

	// Status Current status of the operation
	Status *string `json:"status,omitempty"`

	// TransactionHash Onchain transaction hash which included the operation
	TransactionHash *string `json:"transaction_hash,omitempty"`
}

// OperationRequest defines model for OperationRequest.
type OperationRequest struct {
	// Account Onchain account address performing the operation
	Account string `json:"account"`

	// AccountOperationId Unique account operation identifier
	AccountOperationId string `json:"account_operation_id"`

	// Signature EIP-712 signature of the operation
	Signature    string               `json:"signature"`
	Transactions []TransactionRequest `json:"transactions"`
}

// OperationStatusRequest defines model for OperationStatusRequest.
type OperationStatusRequest struct {
	// Account Onchain account address performing the operation
	Account string `json:"account"`

	// AccountOperationId Unique account operation identifier
	AccountOperationId string `json:"account_operation_id"`

	// TransactionHash Onchain transaction hash which included the operation
	TransactionHash string `json:"transaction_hash"`

	// TransactionTimestamp Timestamp of onchain transaction which included the operation
	TransactionTimestamp int `json:"transaction_timestamp"`
}

// TransactionRequest defines model for TransactionRequest.
type TransactionRequest struct {
	// Data Hex-encoded calldata for the transaction
	Data string `json:"data"`

	// To Address receiving the transaction
	To string `json:"to"`

	// Value Amount of native token value being sent in the transaction
	Value string `json:"value"`
}

// GetEventsParams defines parameters for GetEvents.
type GetEventsParams struct {
	// CreatedLt Filter events created before this timestamp
	CreatedLt *int64 `form:"created.lt,omitempty" json:"created.lt,omitempty"`

	// CreatedLte Filter events created at or before this timestamp
	CreatedLte *int64 `form:"created.lte,omitempty" json:"created.lte,omitempty"`

	// CreatedGt Filter events created after this timestamp
	CreatedGt *int64 `form:"created.gt,omitempty" json:"created.gt,omitempty"`

	// CreatedGte Filter events created at or after this timestamp
	CreatedGte *int64 `form:"created.gte,omitempty" json:"created.gte,omitempty"`

	// Limit The number of events to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// StartingAfter Return events starting after this event UUID
	StartingAfter *openapi_types.UUID `form:"starting_after,omitempty" json:"starting_after,omitempty"`

	// EndingBefore Return events occurring before this event UUID
	EndingBefore *openapi_types.UUID `form:"ending_before,omitempty" json:"ending_before,omitempty"`
}

// GetOperationStatusParams defines parameters for GetOperationStatus.
type GetOperationStatusParams struct {
	// CreatedLt Filter operations created before this timestamp
	CreatedLt *int64 `form:"created.lt,omitempty" json:"created.lt,omitempty"`

	// CreatedLte Filter operations created at or before this timestamp
	CreatedLte *int64 `form:"created.lte,omitempty" json:"created.lte,omitempty"`

	// CreatedGt Filter operations created after this timestamp
	CreatedGt *int64 `form:"created.gt,omitempty" json:"created.gt,omitempty"`

	// CreatedGte Filter operations created at or after this timestamp
	CreatedGte *int64 `form:"created.gte,omitempty" json:"created.gte,omitempty"`

	// Limit The number of operations to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// StartingAfter Return operations starting after this operation UUID
	StartingAfter *openapi_types.UUID `form:"starting_after,omitempty" json:"starting_after,omitempty"`

	// EndingBefore Return operations occurring before this operation UUID
	EndingBefore *openapi_types.UUID `form:"ending_before,omitempty" json:"ending_before,omitempty"`
}

// PostEventsJSONRequestBody defines body for PostEvents for application/json ContentType.
type PostEventsJSONRequestBody = EventRequest

// PostListenerJSONRequestBody defines body for PostListener for application/json ContentType.
type PostListenerJSONRequestBody = ListenerRequest

// PostOperationSendJSONRequestBody defines body for PostOperationSend for application/json ContentType.
type PostOperationSendJSONRequestBody = OperationRequest

// PostOperationStatusJSONRequestBody defines body for PostOperationStatus for application/json ContentType.
type PostOperationStatusJSONRequestBody = OperationStatusRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Retrieves events.
	// (GET /events)
	GetEvents(w http.ResponseWriter, r *http.Request, params GetEventsParams)
	// Creates a new event.
	// (POST /events)
	PostEvents(w http.ResponseWriter, r *http.Request)
	// Health check endpoint
	// (GET /health-check)
	GetHealthCheck(w http.ResponseWriter, r *http.Request)
	// Creates a new listener.
	// (POST /listener)
	PostListener(w http.ResponseWriter, r *http.Request)
	// Sends an onchain transaction event.
	// (POST /operation/send)
	PostOperationSend(w http.ResponseWriter, r *http.Request)
	// Retrieves operation statuses.
	// (GET /operation/status)
	GetOperationStatus(w http.ResponseWriter, r *http.Request, params GetOperationStatusParams)
	// Updates the status of an operation.
	// (POST /operation/status)
	PostOperationStatus(w http.ResponseWriter, r *http.Request)
	// Retrieves the status of an operation.
	// (GET /operation/status/{operation_id})
	GetOperationStatusOperationId(w http.ResponseWriter, r *http.Request, operationId openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetEvents operation middleware
func (siw *ServerInterfaceWrapper) GetEvents(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEventsParams

	// ------------- Optional query parameter "created.lt" -------------

	err = runtime.BindQueryParameter("form", true, false, "created.lt", r.URL.Query(), &params.CreatedLt)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created.lt", Err: err})
		return
	}

	// ------------- Optional query parameter "created.lte" -------------

	err = runtime.BindQueryParameter("form", true, false, "created.lte", r.URL.Query(), &params.CreatedLte)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created.lte", Err: err})
		return
	}

	// ------------- Optional query parameter "created.gt" -------------

	err = runtime.BindQueryParameter("form", true, false, "created.gt", r.URL.Query(), &params.CreatedGt)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created.gt", Err: err})
		return
	}

	// ------------- Optional query parameter "created.gte" -------------

	err = runtime.BindQueryParameter("form", true, false, "created.gte", r.URL.Query(), &params.CreatedGte)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created.gte", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "starting_after" -------------

	err = runtime.BindQueryParameter("form", true, false, "starting_after", r.URL.Query(), &params.StartingAfter)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "starting_after", Err: err})
		return
	}

	// ------------- Optional query parameter "ending_before" -------------

	err = runtime.BindQueryParameter("form", true, false, "ending_before", r.URL.Query(), &params.EndingBefore)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ending_before", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostEvents operation middleware
func (siw *ServerInterfaceWrapper) PostEvents(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEvents(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthCheck operation middleware
func (siw *ServerInterfaceWrapper) GetHealthCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostListener operation middleware
func (siw *ServerInterfaceWrapper) PostListener(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostListener(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostOperationSend operation middleware
func (siw *ServerInterfaceWrapper) PostOperationSend(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostOperationSend(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOperationStatus operation middleware
func (siw *ServerInterfaceWrapper) GetOperationStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetOperationStatusParams

	// ------------- Optional query parameter "created.lt" -------------

	err = runtime.BindQueryParameter("form", true, false, "created.lt", r.URL.Query(), &params.CreatedLt)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created.lt", Err: err})
		return
	}

	// ------------- Optional query parameter "created.lte" -------------

	err = runtime.BindQueryParameter("form", true, false, "created.lte", r.URL.Query(), &params.CreatedLte)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created.lte", Err: err})
		return
	}

	// ------------- Optional query parameter "created.gt" -------------

	err = runtime.BindQueryParameter("form", true, false, "created.gt", r.URL.Query(), &params.CreatedGt)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created.gt", Err: err})
		return
	}

	// ------------- Optional query parameter "created.gte" -------------

	err = runtime.BindQueryParameter("form", true, false, "created.gte", r.URL.Query(), &params.CreatedGte)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created.gte", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "starting_after" -------------

	err = runtime.BindQueryParameter("form", true, false, "starting_after", r.URL.Query(), &params.StartingAfter)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "starting_after", Err: err})
		return
	}

	// ------------- Optional query parameter "ending_before" -------------

	err = runtime.BindQueryParameter("form", true, false, "ending_before", r.URL.Query(), &params.EndingBefore)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ending_before", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOperationStatus(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostOperationStatus operation middleware
func (siw *ServerInterfaceWrapper) PostOperationStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostOperationStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOperationStatusOperationId operation middleware
func (siw *ServerInterfaceWrapper) GetOperationStatusOperationId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "operation_id" -------------
	var operationId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "operation_id", r.PathValue("operation_id"), &operationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "operation_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOperationStatusOperationId(w, r, operationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/events", wrapper.GetEvents)
	m.HandleFunc("POST "+options.BaseURL+"/events", wrapper.PostEvents)
	m.HandleFunc("GET "+options.BaseURL+"/health-check", wrapper.GetHealthCheck)
	m.HandleFunc("POST "+options.BaseURL+"/listener", wrapper.PostListener)
	m.HandleFunc("POST "+options.BaseURL+"/operation/send", wrapper.PostOperationSend)
	m.HandleFunc("GET "+options.BaseURL+"/operation/status", wrapper.GetOperationStatus)
	m.HandleFunc("POST "+options.BaseURL+"/operation/status", wrapper.PostOperationStatus)
	m.HandleFunc("GET "+options.BaseURL+"/operation/status/{operation_id}", wrapper.GetOperationStatusOperationId)

	return m
}
