package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"go/token"
	"go/types"
	"log"
	"os"
	"path"
	"sort"
	"strings"
	"unicode"

	"golang.org/x/tools/go/packages"
)

func main() {
	pkgPath := flag.String("pkg", "", "import path of the source package to mirror (e.g. github.com/smartcontractkit/cvn-api-go/client)")
	out := flag.String("out", "aliases.gen.go", "output file path")
	pkgName := flag.String("pkgname", "", "package name for the output file (must match target dir package)")
	importAlias := flag.String("alias", "", "import alias to use for the mirrored package; defaults to last path element")
	flag.Parse()

	if *pkgPath == "" {
		log.Fatal("missing -pkg import path")
	}
	if *pkgName == "" {
		log.Fatal("missing -pkgname (must match the package where the generated file will live)")
	}
	if *importAlias == "" {
		*importAlias = safeAlias(path.Base(*pkgPath))
	}

	cfg := &packages.Config{
		Mode: packages.NeedName |
			packages.NeedTypes |
			packages.NeedTypesInfo |
			packages.NeedFiles |
			packages.NeedCompiledGoFiles |
			packages.NeedModule,
	}

	pkgs, err := packages.Load(cfg, *pkgPath)
	if err != nil {
		log.Fatalf("packages.Load: %v", err)
	}
	if packages.PrintErrors(pkgs) > 0 || len(pkgs) == 0 {
		log.Fatalf("failed to load package %q", *pkgPath)
	}
	srcPkg := pkgs[0]
	scope := srcPkg.Types.Scope()

	// Collect exported named types we want to alias: structs, interfaces, enums (named + basic underlying).
	typeNames := make([]string, 0, scope.Len())
	typeParamNames := map[string][]string{}       // name -> type param list for generics
	aliasableTypeSet := make(map[string]struct{}) // for deciding typed consts

	for _, name := range scope.Names() {
		if !token.IsExported(name) {
			continue
		}
		obj := scope.Lookup(name)
		tname, ok := obj.(*types.TypeName)
		if !ok {
			continue
		}
		named, ok := tname.Type().(*types.Named)
		if !ok {
			continue
		}

		switch named.Underlying().(type) {
		case *types.Struct, *types.Interface:
			// Always alias exported structs/interfaces
			typeNames = append(typeNames, name)
			aliasableTypeSet[name] = struct{}{}
			if tparams := named.TypeParams(); tparams != nil && tparams.Len() > 0 {
				params := make([]string, tparams.Len())
				for i := 0; i < tparams.Len(); i++ {
					params[i] = tparams.At(i).Obj().Name()
				}
				typeParamNames[name] = params
			}
		case *types.Basic:
			// Treat exported named basic-underlying as enum (e.g., type Status int)
			// Skip predeclared-named proxies (shouldn't appear here) and non-exported
			typeNames = append(typeNames, name)
			aliasableTypeSet[name] = struct{}{}
			// generics can't be basic-underlying, but no harm if empty
		default:
			// skip other underlying kinds (slices, maps, funcs, aliases to complex shapes)
			// If you want to alias *all* named types, drop this switch and just append.
		}
	}

	sort.Strings(typeNames)

	// Collect exported consts (we’ll type them if their type is one of our aliased named types)
	consts := make([]constInfo, 0, 64)
	for _, name := range scope.Names() {
		if !token.IsExported(name) {
			continue
		}
		obj := scope.Lookup(name)
		c, ok := obj.(*types.Const)
		if !ok {
			continue
		}
		// Determine if its type is a named type we’re aliasing; if so, we can emit a typed const.
		var localTypeName string
		if nt, ok := c.Type().(*types.Named); ok {
			tn := nt.Obj().Name()
			if _, present := aliasableTypeSet[tn]; present {
				localTypeName = tn // refers to our alias name in this package
			}
		}
		consts = append(consts, constInfo{
			Name:          name,
			LocalTypeName: localTypeName, // empty => emit untyped const
		})
	}
	sort.Slice(consts, func(i, j int) bool { return consts[i].Name < consts[j].Name })

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by genaliases; DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "package %s\n\n", *pkgName)
	fmt.Fprintf(&buf, "import %s \"%s\"\n\n", *importAlias, *pkgPath)

	// Emit types
	if len(typeNames) > 0 {
		fmt.Fprintf(&buf, "type (\n")
		for _, n := range typeNames {
			if params, ok := typeParamNames[n]; ok && len(params) > 0 {
				// generic named type
				fmt.Fprintf(&buf, "\t%[1]s[%[2]s] = %s.%[1]s[%[2]s]\n", n, strings.Join(params, ", "), *importAlias)
			} else {
				fmt.Fprintf(&buf, "\t%s = %s.%s\n", n, *importAlias, n)
			}
		}
		fmt.Fprintf(&buf, ")\n\n")
	}

	// Emit consts (mirror). If we know the enum type locally, type the const; else leave untyped.
	if len(consts) > 0 {
		fmt.Fprintf(&buf, "const (\n")
		for _, k := range consts {
			if k.LocalTypeName != "" {
				fmt.Fprintf(&buf, "\t%[1]s %[2]s = %s.%[1]s\n", k.Name, k.LocalTypeName, *importAlias)
			} else {
				fmt.Fprintf(&buf, "\t%[1]s = %s.%[1]s\n", k.Name, *importAlias)
			}
		}
		fmt.Fprintf(&buf, ")\n")
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		// Write unformatted output for debugging on failure.
		_ = os.WriteFile(*out, buf.Bytes(), 0o644)
		log.Fatalf("go/format failed; wrote unformatted output to %s: %v", *out, err)
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		log.Fatal(err)
	}
}

type constInfo struct {
	Name          string
	LocalTypeName string // if non-empty, we type the const as this local alias name
}

func safeAlias(s string) string {
	// avoid handful of common collisions; prefix with src + UpperFirst
	switch s {
	case "client", "types", "errors", "token":
		return "src" + upperFirst(s)
	}
	return s
}

func upperFirst(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	r[0] = unicode.ToUpper(r[0])
	return string(r)
}
