package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"go/token"
	"go/types"
	"log"
	"os"
	"path"
	"sort"
	"strings"
	"unicode"

	"golang.org/x/tools/go/packages"
)

func main() {
	pkgPath := flag.String("pkg", "", "import path of the source package to mirror (e.g. example.com/otherpkg/client)")
	out := flag.String("out", "aliases.go", "output file path")
	pkgName := flag.String("pkgname", "yourpkg", "package name for the output file")
	importAlias := flag.String("alias", "", "import alias to use; defaults to last path element")
	flag.Parse()

	if *pkgPath == "" {
		log.Fatal("missing -pkg import path")
	}
	if *importAlias == "" {
		*importAlias = safeAlias(path.Base(*pkgPath))
	}

	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedTypes | packages.NeedTypesInfo | packages.NeedFiles | packages.NeedCompiledGoFiles | packages.NeedModule,
	}
	pkgs, err := packages.Load(cfg, *pkgPath)
	if err != nil {
		log.Fatalf("packages.Load: %v", err)
	}
	if packages.PrintErrors(pkgs) > 0 || len(pkgs) == 0 {
		log.Fatalf("failed to load package %q", *pkgPath)
	}
	p := pkgs[0]
	scope := p.Types.Scope()

	var names []string
	typeParamNames := map[string][]string{} // for generics awareness

	for _, name := range scope.Names() {
		if !token.IsExported(name) {
			continue
		}
		obj, ok := scope.Lookup(name).(*types.TypeName)
		if !ok {
			continue
		}
		named, ok := obj.Type().(*types.Named)
		if !ok {
			continue
		}
		// Underlying must be a struct to match your requirement.
		if _, ok := named.Underlying().(*types.Struct); !ok {
			continue
		}
		names = append(names, name)

		// Capture type parameters if any (for generic structs).
		if tparams := named.TypeParams(); tparams != nil && tparams.Len() > 0 {
			params := make([]string, tparams.Len())
			for i := 0; i < tparams.Len(); i++ {
				params[i] = tparams.At(i).Obj().Name()
			}
			typeParamNames[name] = params
		}
	}

	sort.Strings(names)

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by genaliases; DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "package %s\n\n", *pkgName)
	fmt.Fprintf(&buf, "import %s \"%s\"\n\n", *importAlias, *pkgPath)
	fmt.Fprintf(&buf, "type (\n")
	for _, n := range names {
		if params, ok := typeParamNames[n]; ok && len(params) > 0 {
			// e.g., type Foo[T any, U comparable] = otherpkg.Foo[T, U]
			fmt.Fprintf(&buf, "\t%[1]s[%[2]s] = %s.%[1]s[%[2]s]\n", n, strings.Join(params, ", "), *importAlias)
		} else {
			fmt.Fprintf(&buf, "\t%s = %s.%s\n", n, *importAlias, n)
		}
	}
	fmt.Fprintf(&buf, ")\n")

	src, err := format.Source(buf.Bytes())
	if err != nil {
		// If formatting fails, dump raw for debugging.
		_ = os.WriteFile(*out, buf.Bytes(), 0o644)
		log.Fatalf("go/format failed; wrote unformatted output to %s: %v", *out, err)
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		log.Fatal(err)
	}
}

func safeAlias(s string) string {
	// Avoid reserved words and invalid identifiers minimally.
	switch s {
	case "client", "types", "errors", "token":
		return "src" + upperFirst(s)
	}
	return s
}

func upperFirst(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	r[0] = unicode.ToUpper(r[0])
	return string(r)
}
