name: Go Unit Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci-lint-go:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: ci-lint-go
        uses: smartcontractkit/.github/actions/ci-lint-go@6ff93d190d3499c4889001c181f503c45420497d # ci-lint-go@4.2.0
        with:
          go-version-file: go.mod
          golangci-lint-version: v2.12.2
          use-go-cache: true
          only-new-issues: false
          use-gati: false
          golangci-lint-args: --timeout=5m

  ci-test-go:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: ci-test-go
        uses: smartcontractkit/.github/actions/ci-test-go@2b1d964024bb001ae9fba4f840019ac86ad1d824 # ci-test-go/v1
        with:
          use-gati: false
          go-test-cmd: go test ./...
          use-go-cache: true