name: Go Unit Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci-test-go:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: ci-test-go
        uses: smartcontractkit/.github/actions/ci-test-go@6ff93d190d3499c4889001c181f503c45420497d # ci-test-go/v1
        with:
          use-gati: false
          go-test-cmd: go test ./...
          use-go-cache: true