name: Go CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  ci-test-go:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: ci-test-go
        uses: smartcontractkit/.github/actions/ci-test-go@2b1d964024bb001ae9fba4f840019ac86ad1d824 # ci-test-go/v1
        with:
          use-gati: false
          go-test-cmd: go test ./...
          use-go-cache: true

  lint-go:
    name: Go Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
          cache: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12